//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaDocumentoArrecadacaoDarWeb
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", ConfigurationName="ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS")]
    public interface ConsultaDocumentoArrecadacaoWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosN" +
            "aoPagosRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosN" +
            "aoPagosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosNaoPagosResponse> consultarDocumentosNaoPagosAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosNaoPagosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosE" +
            "mitidosRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosE" +
            "mitidosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosResponse> consultarDocumentosEmitidosAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosP" +
            "orNumeroDocumentoRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosP" +
            "orNumeroDocumentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroDocumentoResponse> consultarDocumentosPorNumeroDocumentoAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosP" +
            "orNumeroControleRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosP" +
            "orNumeroControleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroControleResponse> consultarDocumentosPorNumeroControleAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroControleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosE" +
            "mitidosPorNumerosDocumentosRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosE" +
            "mitidosPorNumerosDocumentosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorNumerosDocumentosResponse> consultarDocumentosEmitidosPorNumerosDocumentosAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorNumerosDocumentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosE" +
            "mitidosPorPeriodoReferenciaRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosE" +
            "mitidosPorPeriodoReferenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorPeriodoReferenciaResponse> consultarDocumentosEmitidosPorPeriodoReferenciaAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorPeriodoReferenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosE" +
            "mitidosPorCpfCnpjIERequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosE" +
            "mitidosPorCpfCnpjIEResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorCpfCnpjIEResponse> consultarDocumentosEmitidosPorCpfCnpjIEAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorCpfCnpjIERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosE" +
            "mitidosPorIntervaloDataRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosE" +
            "mitidosPorIntervaloDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorIntervaloDataResponse> consultarDocumentosEmitidosPorIntervaloDataAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorIntervaloDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosP" +
            "agosRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarDocumentosP" +
            "agosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPagosResponse> consultarDocumentosPagosAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPagosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/boletoPDFRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/boletoPDFResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.boletoPDFResponse> boletoPDFAsync(ConsultaDocumentoArrecadacaoDarWeb.boletoPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarPDFPorNumer" +
            "oControleRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/ConsultaDocumentoArrecadacaoWS/consultarPDFPorNumer" +
            "oControleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarPDFPorNumeroControleResponse> consultarPDFPorNumeroControleAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarPDFPorNumeroControleRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/")]
    public partial class consultaBoletoRetorno : mensagemRetorno
    {
        
        private boletoRetorno[] boletoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("boleto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public boletoRetorno[] boleto
        {
            get
            {
                return this.boletoField;
            }
            set
            {
                this.boletoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/")]
    public partial class boletoRetorno : mensagemRetorno
    {
        
        private string boletoBytesField;
        
        private string codigoBarrasField;
        
        private string dataPagamentoField;
        
        private boletoImpresso impressaoField;
        
        private string linhaDigitavelField;
        
        private string numeroControleField;
        
        private string numeroDocumentoField;
        
        private string pagoField;
        
        private string valorPagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string boletoBytes
        {
            get
            {
                return this.boletoBytesField;
            }
            set
            {
                this.boletoBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoBarras
        {
            get
            {
                return this.codigoBarrasField;
            }
            set
            {
                this.codigoBarrasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dataPagamento
        {
            get
            {
                return this.dataPagamentoField;
            }
            set
            {
                this.dataPagamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public boletoImpresso impressao
        {
            get
            {
                return this.impressaoField;
            }
            set
            {
                this.impressaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string linhaDigitavel
        {
            get
            {
                return this.linhaDigitavelField;
            }
            set
            {
                this.linhaDigitavelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string numeroControle
        {
            get
            {
                return this.numeroControleField;
            }
            set
            {
                this.numeroControleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string pago
        {
            get
            {
                return this.pagoField;
            }
            set
            {
                this.pagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string valorPago
        {
            get
            {
                return this.valorPagoField;
            }
            set
            {
                this.valorPagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/")]
    public partial class boletoImpresso
    {
        
        private string bairroField;
        
        private string cepField;
        
        private string chassiField;
        
        private string cnpjCpfField;
        
        private string codigoBarrasField;
        
        private string codigoBarrasArmazenadoField;
        
        private string codigoReceitaField;
        
        private string codigoReceitaPagoField;
        
        private string correcaoField;
        
        private string dataGeracaoField;
        
        private string dataPagamentoField;
        
        private string dataVencimentoField;
        
        private string descricaoCodigoReceitaField;
        
        private string emailField;
        
        private string enderecoField;
        
        private string icmsComplementarField;
        
        private string inscricaoField;
        
        private double juroAntecipacaoField;
        
        private string jurosField;
        
        private string linhaDigitavelField;
        
        private string linkbbField;
        
        private string mensagemMultasField;
        
        private string multaField;
        
        private string multaAcessoriaField;
        
        private double multaAntecipacaoField;
        
        private string multaPrincipalField;
        
        private string municipioField;
        
        private string nomeMaquinaField;
        
        private string nomeRazaoSocialField;
        
        private string numeroControleField;
        
        private string numeroDocumentoField;
        
        private string numeroDocumentoIdentificacaoField;
        
        private string numeroParcelaField;
        
        private string observacaoField;
        
        private string periodoReferenciaField;
        
        private long renavamField;
        
        private string taxaField;
        
        private string telefoneField;
        
        private string tipoDarField;
        
        private string tipoIdentificacaoField;
        
        private string totalMultasField;
        
        private string ufField;
        
        private double valorAntecipacaoField;
        
        private double valorFecopField;
        
        private string valorOriginalReceitaField;
        
        private string valorPrincipalField;
        
        private string valorPrincipalImpressaoField;
        
        private string valorTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bairro
        {
            get
            {
                return this.bairroField;
            }
            set
            {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cep
        {
            get
            {
                return this.cepField;
            }
            set
            {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string chassi
        {
            get
            {
                return this.chassiField;
            }
            set
            {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cnpjCpf
        {
            get
            {
                return this.cnpjCpfField;
            }
            set
            {
                this.cnpjCpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string codigoBarras
        {
            get
            {
                return this.codigoBarrasField;
            }
            set
            {
                this.codigoBarrasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codigoBarrasArmazenado
        {
            get
            {
                return this.codigoBarrasArmazenadoField;
            }
            set
            {
                this.codigoBarrasArmazenadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string codigoReceita
        {
            get
            {
                return this.codigoReceitaField;
            }
            set
            {
                this.codigoReceitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string codigoReceitaPago
        {
            get
            {
                return this.codigoReceitaPagoField;
            }
            set
            {
                this.codigoReceitaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string correcao
        {
            get
            {
                return this.correcaoField;
            }
            set
            {
                this.correcaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string dataGeracao
        {
            get
            {
                return this.dataGeracaoField;
            }
            set
            {
                this.dataGeracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string dataPagamento
        {
            get
            {
                return this.dataPagamentoField;
            }
            set
            {
                this.dataPagamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string dataVencimento
        {
            get
            {
                return this.dataVencimentoField;
            }
            set
            {
                this.dataVencimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string descricaoCodigoReceita
        {
            get
            {
                return this.descricaoCodigoReceitaField;
            }
            set
            {
                this.descricaoCodigoReceitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string endereco
        {
            get
            {
                return this.enderecoField;
            }
            set
            {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string icmsComplementar
        {
            get
            {
                return this.icmsComplementarField;
            }
            set
            {
                this.icmsComplementarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string inscricao
        {
            get
            {
                return this.inscricaoField;
            }
            set
            {
                this.inscricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public double juroAntecipacao
        {
            get
            {
                return this.juroAntecipacaoField;
            }
            set
            {
                this.juroAntecipacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string juros
        {
            get
            {
                return this.jurosField;
            }
            set
            {
                this.jurosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string linhaDigitavel
        {
            get
            {
                return this.linhaDigitavelField;
            }
            set
            {
                this.linhaDigitavelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string linkbb
        {
            get
            {
                return this.linkbbField;
            }
            set
            {
                this.linkbbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string mensagemMultas
        {
            get
            {
                return this.mensagemMultasField;
            }
            set
            {
                this.mensagemMultasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string multa
        {
            get
            {
                return this.multaField;
            }
            set
            {
                this.multaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string multaAcessoria
        {
            get
            {
                return this.multaAcessoriaField;
            }
            set
            {
                this.multaAcessoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public double multaAntecipacao
        {
            get
            {
                return this.multaAntecipacaoField;
            }
            set
            {
                this.multaAntecipacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string multaPrincipal
        {
            get
            {
                return this.multaPrincipalField;
            }
            set
            {
                this.multaPrincipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string municipio
        {
            get
            {
                return this.municipioField;
            }
            set
            {
                this.municipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string nomeMaquina
        {
            get
            {
                return this.nomeMaquinaField;
            }
            set
            {
                this.nomeMaquinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string nomeRazaoSocial
        {
            get
            {
                return this.nomeRazaoSocialField;
            }
            set
            {
                this.nomeRazaoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string numeroControle
        {
            get
            {
                return this.numeroControleField;
            }
            set
            {
                this.numeroControleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string numeroDocumentoIdentificacao
        {
            get
            {
                return this.numeroDocumentoIdentificacaoField;
            }
            set
            {
                this.numeroDocumentoIdentificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string numeroParcela
        {
            get
            {
                return this.numeroParcelaField;
            }
            set
            {
                this.numeroParcelaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string observacao
        {
            get
            {
                return this.observacaoField;
            }
            set
            {
                this.observacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string periodoReferencia
        {
            get
            {
                return this.periodoReferenciaField;
            }
            set
            {
                this.periodoReferenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public long renavam
        {
            get
            {
                return this.renavamField;
            }
            set
            {
                this.renavamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string taxa
        {
            get
            {
                return this.taxaField;
            }
            set
            {
                this.taxaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string telefone
        {
            get
            {
                return this.telefoneField;
            }
            set
            {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string tipoDar
        {
            get
            {
                return this.tipoDarField;
            }
            set
            {
                this.tipoDarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string tipoIdentificacao
        {
            get
            {
                return this.tipoIdentificacaoField;
            }
            set
            {
                this.tipoIdentificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string totalMultas
        {
            get
            {
                return this.totalMultasField;
            }
            set
            {
                this.totalMultasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string uf
        {
            get
            {
                return this.ufField;
            }
            set
            {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public double valorAntecipacao
        {
            get
            {
                return this.valorAntecipacaoField;
            }
            set
            {
                this.valorAntecipacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public double valorFecop
        {
            get
            {
                return this.valorFecopField;
            }
            set
            {
                this.valorFecopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string valorOriginalReceita
        {
            get
            {
                return this.valorOriginalReceitaField;
            }
            set
            {
                this.valorOriginalReceitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string valorPrincipal
        {
            get
            {
                return this.valorPrincipalField;
            }
            set
            {
                this.valorPrincipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string valorPrincipalImpressao
        {
            get
            {
                return this.valorPrincipalImpressaoField;
            }
            set
            {
                this.valorPrincipalImpressaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string valorTotal
        {
            get
            {
                return this.valorTotalField;
            }
            set
            {
                this.valorTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(boletoRetorno))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(consultaBoletoRetorno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/")]
    public partial class mensagemRetorno
    {
        
        private string mensagemRetorno1Field;
        
        private string tipoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensagemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mensagemRetorno1
        {
            get
            {
                return this.mensagemRetorno1Field;
            }
            set
            {
                this.mensagemRetorno1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoRetorno
        {
            get
            {
                return this.tipoRetornoField;
            }
            set
            {
                this.tipoRetornoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosNaoPagos", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosNaoPagosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public consultarDocumentosNaoPagosRequest()
        {
        }
        
        public consultarDocumentosNaoPagosRequest(string codigoOrgao, string tokenAcesso)
        {
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosNaoPagosResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosNaoPagosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return;
        
        public consultarDocumentosNaoPagosResponse()
        {
        }
        
        public consultarDocumentosNaoPagosResponse(ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosEmitidos", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosEmitidosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public consultarDocumentosEmitidosRequest()
        {
        }
        
        public consultarDocumentosEmitidosRequest(string codigoOrgao, string tokenAcesso)
        {
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosEmitidosResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosEmitidosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return;
        
        public consultarDocumentosEmitidosResponse()
        {
        }
        
        public consultarDocumentosEmitidosResponse(ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosPorNumeroDocumento", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosPorNumeroDocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public consultarDocumentosPorNumeroDocumentoRequest()
        {
        }
        
        public consultarDocumentosPorNumeroDocumentoRequest(string numeroDocumento, string codigoOrgao, string tokenAcesso)
        {
            this.numeroDocumento = numeroDocumento;
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosPorNumeroDocumentoResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosPorNumeroDocumentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return;
        
        public consultarDocumentosPorNumeroDocumentoResponse()
        {
        }
        
        public consultarDocumentosPorNumeroDocumentoResponse(ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosPorNumeroControle", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosPorNumeroControleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroControle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public consultarDocumentosPorNumeroControleRequest()
        {
        }
        
        public consultarDocumentosPorNumeroControleRequest(string numeroControle, string codigoOrgao, string tokenAcesso)
        {
            this.numeroControle = numeroControle;
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosPorNumeroControleResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosPorNumeroControleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return;
        
        public consultarDocumentosPorNumeroControleResponse()
        {
        }
        
        public consultarDocumentosPorNumeroControleResponse(ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosEmitidosPorNumerosDocumentos", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosEmitidosPorNumerosDocumentosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numerosDocumentos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public consultarDocumentosEmitidosPorNumerosDocumentosRequest()
        {
        }
        
        public consultarDocumentosEmitidosPorNumerosDocumentosRequest(string numerosDocumentos, string codigoOrgao, string tokenAcesso)
        {
            this.numerosDocumentos = numerosDocumentos;
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosEmitidosPorNumerosDocumentosResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosEmitidosPorNumerosDocumentosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return;
        
        public consultarDocumentosEmitidosPorNumerosDocumentosResponse()
        {
        }
        
        public consultarDocumentosEmitidosPorNumerosDocumentosResponse(ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosEmitidosPorPeriodoReferencia", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosEmitidosPorPeriodoReferenciaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string periodoReferencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public consultarDocumentosEmitidosPorPeriodoReferenciaRequest()
        {
        }
        
        public consultarDocumentosEmitidosPorPeriodoReferenciaRequest(string periodoReferencia, string codigoOrgao, string tokenAcesso)
        {
            this.periodoReferencia = periodoReferencia;
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosEmitidosPorPeriodoReferenciaResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosEmitidosPorPeriodoReferenciaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return;
        
        public consultarDocumentosEmitidosPorPeriodoReferenciaResponse()
        {
        }
        
        public consultarDocumentosEmitidosPorPeriodoReferenciaResponse(ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosEmitidosPorCpfCnpjIE", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosEmitidosPorCpfCnpjIERequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfCnpjIE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public consultarDocumentosEmitidosPorCpfCnpjIERequest()
        {
        }
        
        public consultarDocumentosEmitidosPorCpfCnpjIERequest(string cpfCnpjIE, string codigoOrgao, string tokenAcesso)
        {
            this.cpfCnpjIE = cpfCnpjIE;
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosEmitidosPorCpfCnpjIEResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosEmitidosPorCpfCnpjIEResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return;
        
        public consultarDocumentosEmitidosPorCpfCnpjIEResponse()
        {
        }
        
        public consultarDocumentosEmitidosPorCpfCnpjIEResponse(ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosEmitidosPorIntervaloData", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosEmitidosPorIntervaloDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataInicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public consultarDocumentosEmitidosPorIntervaloDataRequest()
        {
        }
        
        public consultarDocumentosEmitidosPorIntervaloDataRequest(string dataInicial, string dataFinal, string codigoOrgao, string tokenAcesso)
        {
            this.dataInicial = dataInicial;
            this.dataFinal = dataFinal;
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosEmitidosPorIntervaloDataResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosEmitidosPorIntervaloDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return;
        
        public consultarDocumentosEmitidosPorIntervaloDataResponse()
        {
        }
        
        public consultarDocumentosEmitidosPorIntervaloDataResponse(ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosPagos", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosPagosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public consultarDocumentosPagosRequest()
        {
        }
        
        public consultarDocumentosPagosRequest(string codigoOrgao, string tokenAcesso)
        {
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentosPagosResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarDocumentosPagosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return;
        
        public consultarDocumentosPagosResponse()
        {
        }
        
        public consultarDocumentosPagosResponse(ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="boletoPDF", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class boletoPDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultaDocumentoArrecadacaoDarWeb.boletoImpresso arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public boletoPDFRequest()
        {
        }
        
        public boletoPDFRequest(ConsultaDocumentoArrecadacaoDarWeb.boletoImpresso arg0, string arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="boletoPDFResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class boletoPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public boletoPDFResponse()
        {
        }
        
        public boletoPDFResponse(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarPDFPorNumeroControle", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarPDFPorNumeroControleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroControle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public consultarPDFPorNumeroControleRequest()
        {
        }
        
        public consultarPDFPorNumeroControleRequest(string numeroControle, string codigoOrgao, string tokenAcesso)
        {
            this.numeroControle = numeroControle;
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarPDFPorNumeroControleResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class consultarPDFPorNumeroControleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return;
        
        public consultarPDFPorNumeroControleResponse()
        {
        }
        
        public consultarPDFPorNumeroControleResponse(ConsultaDocumentoArrecadacaoDarWeb.consultaBoletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ConsultaDocumentoArrecadacaoWSChannel : ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ConsultaDocumentoArrecadacaoWSClient : System.ServiceModel.ClientBase<ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS>, ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConsultaDocumentoArrecadacaoWSClient() : 
                base(ConsultaDocumentoArrecadacaoWSClient.GetDefaultBinding(), ConsultaDocumentoArrecadacaoWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ConsultaDocumentoArrecadacaoWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaDocumentoArrecadacaoWSClient(EndpointConfiguration endpointConfiguration) : 
                base(ConsultaDocumentoArrecadacaoWSClient.GetBindingForEndpoint(endpointConfiguration), ConsultaDocumentoArrecadacaoWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaDocumentoArrecadacaoWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConsultaDocumentoArrecadacaoWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaDocumentoArrecadacaoWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConsultaDocumentoArrecadacaoWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaDocumentoArrecadacaoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosNaoPagosResponse> ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS.consultarDocumentosNaoPagosAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosNaoPagosRequest request)
        {
            return base.Channel.consultarDocumentosNaoPagosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosNaoPagosResponse> consultarDocumentosNaoPagosAsync(string codigoOrgao, string tokenAcesso)
        {
            ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosNaoPagosRequest inValue = new ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosNaoPagosRequest();
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS)(this)).consultarDocumentosNaoPagosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosResponse> ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS.consultarDocumentosEmitidosAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosRequest request)
        {
            return base.Channel.consultarDocumentosEmitidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosResponse> consultarDocumentosEmitidosAsync(string codigoOrgao, string tokenAcesso)
        {
            ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosRequest inValue = new ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosRequest();
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS)(this)).consultarDocumentosEmitidosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroDocumentoResponse> ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS.consultarDocumentosPorNumeroDocumentoAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroDocumentoRequest request)
        {
            return base.Channel.consultarDocumentosPorNumeroDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroDocumentoResponse> consultarDocumentosPorNumeroDocumentoAsync(string numeroDocumento, string codigoOrgao, string tokenAcesso)
        {
            ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroDocumentoRequest inValue = new ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroDocumentoRequest();
            inValue.numeroDocumento = numeroDocumento;
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS)(this)).consultarDocumentosPorNumeroDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroControleResponse> ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS.consultarDocumentosPorNumeroControleAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroControleRequest request)
        {
            return base.Channel.consultarDocumentosPorNumeroControleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroControleResponse> consultarDocumentosPorNumeroControleAsync(string numeroControle, string codigoOrgao, string tokenAcesso)
        {
            ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroControleRequest inValue = new ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPorNumeroControleRequest();
            inValue.numeroControle = numeroControle;
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS)(this)).consultarDocumentosPorNumeroControleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorNumerosDocumentosResponse> ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS.consultarDocumentosEmitidosPorNumerosDocumentosAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorNumerosDocumentosRequest request)
        {
            return base.Channel.consultarDocumentosEmitidosPorNumerosDocumentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorNumerosDocumentosResponse> consultarDocumentosEmitidosPorNumerosDocumentosAsync(string numerosDocumentos, string codigoOrgao, string tokenAcesso)
        {
            ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorNumerosDocumentosRequest inValue = new ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorNumerosDocumentosRequest();
            inValue.numerosDocumentos = numerosDocumentos;
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS)(this)).consultarDocumentosEmitidosPorNumerosDocumentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorPeriodoReferenciaResponse> ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS.consultarDocumentosEmitidosPorPeriodoReferenciaAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorPeriodoReferenciaRequest request)
        {
            return base.Channel.consultarDocumentosEmitidosPorPeriodoReferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorPeriodoReferenciaResponse> consultarDocumentosEmitidosPorPeriodoReferenciaAsync(string periodoReferencia, string codigoOrgao, string tokenAcesso)
        {
            ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorPeriodoReferenciaRequest inValue = new ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorPeriodoReferenciaRequest();
            inValue.periodoReferencia = periodoReferencia;
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS)(this)).consultarDocumentosEmitidosPorPeriodoReferenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorCpfCnpjIEResponse> ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS.consultarDocumentosEmitidosPorCpfCnpjIEAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorCpfCnpjIERequest request)
        {
            return base.Channel.consultarDocumentosEmitidosPorCpfCnpjIEAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorCpfCnpjIEResponse> consultarDocumentosEmitidosPorCpfCnpjIEAsync(string cpfCnpjIE, string codigoOrgao, string tokenAcesso)
        {
            ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorCpfCnpjIERequest inValue = new ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorCpfCnpjIERequest();
            inValue.cpfCnpjIE = cpfCnpjIE;
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS)(this)).consultarDocumentosEmitidosPorCpfCnpjIEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorIntervaloDataResponse> ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS.consultarDocumentosEmitidosPorIntervaloDataAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorIntervaloDataRequest request)
        {
            return base.Channel.consultarDocumentosEmitidosPorIntervaloDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorIntervaloDataResponse> consultarDocumentosEmitidosPorIntervaloDataAsync(string dataInicial, string dataFinal, string codigoOrgao, string tokenAcesso)
        {
            ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorIntervaloDataRequest inValue = new ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosEmitidosPorIntervaloDataRequest();
            inValue.dataInicial = dataInicial;
            inValue.dataFinal = dataFinal;
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS)(this)).consultarDocumentosEmitidosPorIntervaloDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPagosResponse> ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS.consultarDocumentosPagosAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPagosRequest request)
        {
            return base.Channel.consultarDocumentosPagosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPagosResponse> consultarDocumentosPagosAsync(string codigoOrgao, string tokenAcesso)
        {
            ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPagosRequest inValue = new ConsultaDocumentoArrecadacaoDarWeb.consultarDocumentosPagosRequest();
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS)(this)).consultarDocumentosPagosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.boletoPDFResponse> ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS.boletoPDFAsync(ConsultaDocumentoArrecadacaoDarWeb.boletoPDFRequest request)
        {
            return base.Channel.boletoPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.boletoPDFResponse> boletoPDFAsync(ConsultaDocumentoArrecadacaoDarWeb.boletoImpresso arg0, string arg1)
        {
            ConsultaDocumentoArrecadacaoDarWeb.boletoPDFRequest inValue = new ConsultaDocumentoArrecadacaoDarWeb.boletoPDFRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS)(this)).boletoPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarPDFPorNumeroControleResponse> ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS.consultarPDFPorNumeroControleAsync(ConsultaDocumentoArrecadacaoDarWeb.consultarPDFPorNumeroControleRequest request)
        {
            return base.Channel.consultarPDFPorNumeroControleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaDocumentoArrecadacaoDarWeb.consultarPDFPorNumeroControleResponse> consultarPDFPorNumeroControleAsync(string numeroControle, string codigoOrgao, string tokenAcesso)
        {
            ConsultaDocumentoArrecadacaoDarWeb.consultarPDFPorNumeroControleRequest inValue = new ConsultaDocumentoArrecadacaoDarWeb.consultarPDFPorNumeroControleRequest();
            inValue.numeroControle = numeroControle;
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((ConsultaDocumentoArrecadacaoDarWeb.ConsultaDocumentoArrecadacaoWS)(this)).consultarPDFPorNumeroControleAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConsultaDocumentoArrecadacaoWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConsultaDocumentoArrecadacaoWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://webas.sefaz.pi.gov.br/emiteDarService-homolog/ConsultaDocumentoArrecadacao" +
                        "WS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConsultaDocumentoArrecadacaoWSClient.GetBindingForEndpoint(EndpointConfiguration.ConsultaDocumentoArrecadacaoWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConsultaDocumentoArrecadacaoWSClient.GetEndpointAddress(EndpointConfiguration.ConsultaDocumentoArrecadacaoWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ConsultaDocumentoArrecadacaoWSPort,
        }
    }
}
