//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationDarService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", ConfigurationName="IntegrationDarService.DocumentoArrecadacaoWS")]
    public interface DocumentoArrecadacaoWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarCodigoBarrasIPVAReq" +
            "uest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarCodigoBarrasIPVARes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasIPVAResponse> solicitarCodigoBarrasIPVAAsync(IntegrationDarService.solicitarCodigoBarrasIPVARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarCodigoBarrasRequest" +
            "", ReplyAction="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarCodigoBarrasRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasResponse> solicitarCodigoBarrasAsync(IntegrationDarService.solicitarCodigoBarrasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarCodigoBarrasPDFRequ" +
            "est", ReplyAction="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarCodigoBarrasPDFResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasPDFResponse> solicitarCodigoBarrasPDFAsync(IntegrationDarService.solicitarCodigoBarrasPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarDarIcmsRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarDarIcmsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarDarIcmsResponse> solicitarDarIcmsAsync(IntegrationDarService.solicitarDarIcmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarDarAInfracaoAvisoDe" +
            "bRequest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarDarAInfracaoAvisoDe" +
            "bResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarDarAInfracaoAvisoDebResponse> solicitarDarAInfracaoAvisoDebAsync(IntegrationDarService.solicitarDarAInfracaoAvisoDebRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/")]
    public partial class boletoRetorno : mensagemRetorno
    {
        
        private string boletoBytesField;
        
        private string codigoBarrasField;
        
        private string dataPagamentoField;
        
        private boletoImpresso impressaoField;
        
        private string linhaDigitavelField;
        
        private string numeroControleField;
        
        private string numeroDocumentoField;
        
        private string pagoField;
        
        private string valorPagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string boletoBytes
        {
            get
            {
                return this.boletoBytesField;
            }
            set
            {
                this.boletoBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoBarras
        {
            get
            {
                return this.codigoBarrasField;
            }
            set
            {
                this.codigoBarrasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dataPagamento
        {
            get
            {
                return this.dataPagamentoField;
            }
            set
            {
                this.dataPagamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public boletoImpresso impressao
        {
            get
            {
                return this.impressaoField;
            }
            set
            {
                this.impressaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string linhaDigitavel
        {
            get
            {
                return this.linhaDigitavelField;
            }
            set
            {
                this.linhaDigitavelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string numeroControle
        {
            get
            {
                return this.numeroControleField;
            }
            set
            {
                this.numeroControleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string pago
        {
            get
            {
                return this.pagoField;
            }
            set
            {
                this.pagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string valorPago
        {
            get
            {
                return this.valorPagoField;
            }
            set
            {
                this.valorPagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/")]
    public partial class boletoImpresso
    {
        
        private string bairroField;
        
        private string cepField;
        
        private string chassiField;
        
        private string cnpjCpfField;
        
        private string codigoBarrasField;
        
        private string codigoBarrasArmazenadoField;
        
        private string codigoReceitaField;
        
        private string codigoReceitaPagoField;
        
        private string correcaoField;
        
        private string dataGeracaoField;
        
        private string dataPagamentoField;
        
        private string dataVencimentoField;
        
        private string descricaoCodigoReceitaField;
        
        private string emailField;
        
        private string enderecoField;
        
        private string icmsComplementarField;
        
        private string inscricaoField;
        
        private double juroAntecipacaoField;
        
        private string jurosField;
        
        private string linhaDigitavelField;
        
        private string linkbbField;
        
        private string mensagemMultasField;
        
        private string multaField;
        
        private string multaAcessoriaField;
        
        private double multaAntecipacaoField;
        
        private string multaPrincipalField;
        
        private string municipioField;
        
        private string nomeMaquinaField;
        
        private string nomeRazaoSocialField;
        
        private string numeroControleField;
        
        private string numeroDocumentoField;
        
        private string numeroDocumentoIdentificacaoField;
        
        private string numeroParcelaField;
        
        private string observacaoField;
        
        private string periodoReferenciaField;
        
        private long renavamField;
        
        private string taxaField;
        
        private string telefoneField;
        
        private string tipoDarField;
        
        private string tipoIdentificacaoField;
        
        private string totalMultasField;
        
        private string ufField;
        
        private double valorAntecipacaoField;
        
        private double valorFecopField;
        
        private string valorOriginalReceitaField;
        
        private string valorPrincipalField;
        
        private string valorPrincipalImpressaoField;
        
        private string valorTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bairro
        {
            get
            {
                return this.bairroField;
            }
            set
            {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cep
        {
            get
            {
                return this.cepField;
            }
            set
            {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string chassi
        {
            get
            {
                return this.chassiField;
            }
            set
            {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cnpjCpf
        {
            get
            {
                return this.cnpjCpfField;
            }
            set
            {
                this.cnpjCpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string codigoBarras
        {
            get
            {
                return this.codigoBarrasField;
            }
            set
            {
                this.codigoBarrasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codigoBarrasArmazenado
        {
            get
            {
                return this.codigoBarrasArmazenadoField;
            }
            set
            {
                this.codigoBarrasArmazenadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string codigoReceita
        {
            get
            {
                return this.codigoReceitaField;
            }
            set
            {
                this.codigoReceitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string codigoReceitaPago
        {
            get
            {
                return this.codigoReceitaPagoField;
            }
            set
            {
                this.codigoReceitaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string correcao
        {
            get
            {
                return this.correcaoField;
            }
            set
            {
                this.correcaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string dataGeracao
        {
            get
            {
                return this.dataGeracaoField;
            }
            set
            {
                this.dataGeracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string dataPagamento
        {
            get
            {
                return this.dataPagamentoField;
            }
            set
            {
                this.dataPagamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string dataVencimento
        {
            get
            {
                return this.dataVencimentoField;
            }
            set
            {
                this.dataVencimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string descricaoCodigoReceita
        {
            get
            {
                return this.descricaoCodigoReceitaField;
            }
            set
            {
                this.descricaoCodigoReceitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string endereco
        {
            get
            {
                return this.enderecoField;
            }
            set
            {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string icmsComplementar
        {
            get
            {
                return this.icmsComplementarField;
            }
            set
            {
                this.icmsComplementarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string inscricao
        {
            get
            {
                return this.inscricaoField;
            }
            set
            {
                this.inscricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public double juroAntecipacao
        {
            get
            {
                return this.juroAntecipacaoField;
            }
            set
            {
                this.juroAntecipacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string juros
        {
            get
            {
                return this.jurosField;
            }
            set
            {
                this.jurosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string linhaDigitavel
        {
            get
            {
                return this.linhaDigitavelField;
            }
            set
            {
                this.linhaDigitavelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string linkbb
        {
            get
            {
                return this.linkbbField;
            }
            set
            {
                this.linkbbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string mensagemMultas
        {
            get
            {
                return this.mensagemMultasField;
            }
            set
            {
                this.mensagemMultasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string multa
        {
            get
            {
                return this.multaField;
            }
            set
            {
                this.multaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string multaAcessoria
        {
            get
            {
                return this.multaAcessoriaField;
            }
            set
            {
                this.multaAcessoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public double multaAntecipacao
        {
            get
            {
                return this.multaAntecipacaoField;
            }
            set
            {
                this.multaAntecipacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string multaPrincipal
        {
            get
            {
                return this.multaPrincipalField;
            }
            set
            {
                this.multaPrincipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string municipio
        {
            get
            {
                return this.municipioField;
            }
            set
            {
                this.municipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string nomeMaquina
        {
            get
            {
                return this.nomeMaquinaField;
            }
            set
            {
                this.nomeMaquinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string nomeRazaoSocial
        {
            get
            {
                return this.nomeRazaoSocialField;
            }
            set
            {
                this.nomeRazaoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string numeroControle
        {
            get
            {
                return this.numeroControleField;
            }
            set
            {
                this.numeroControleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string numeroDocumentoIdentificacao
        {
            get
            {
                return this.numeroDocumentoIdentificacaoField;
            }
            set
            {
                this.numeroDocumentoIdentificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string numeroParcela
        {
            get
            {
                return this.numeroParcelaField;
            }
            set
            {
                this.numeroParcelaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string observacao
        {
            get
            {
                return this.observacaoField;
            }
            set
            {
                this.observacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string periodoReferencia
        {
            get
            {
                return this.periodoReferenciaField;
            }
            set
            {
                this.periodoReferenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public long renavam
        {
            get
            {
                return this.renavamField;
            }
            set
            {
                this.renavamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string taxa
        {
            get
            {
                return this.taxaField;
            }
            set
            {
                this.taxaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string telefone
        {
            get
            {
                return this.telefoneField;
            }
            set
            {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string tipoDar
        {
            get
            {
                return this.tipoDarField;
            }
            set
            {
                this.tipoDarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string tipoIdentificacao
        {
            get
            {
                return this.tipoIdentificacaoField;
            }
            set
            {
                this.tipoIdentificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string totalMultas
        {
            get
            {
                return this.totalMultasField;
            }
            set
            {
                this.totalMultasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string uf
        {
            get
            {
                return this.ufField;
            }
            set
            {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public double valorAntecipacao
        {
            get
            {
                return this.valorAntecipacaoField;
            }
            set
            {
                this.valorAntecipacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public double valorFecop
        {
            get
            {
                return this.valorFecopField;
            }
            set
            {
                this.valorFecopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string valorOriginalReceita
        {
            get
            {
                return this.valorOriginalReceitaField;
            }
            set
            {
                this.valorOriginalReceitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string valorPrincipal
        {
            get
            {
                return this.valorPrincipalField;
            }
            set
            {
                this.valorPrincipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string valorPrincipalImpressao
        {
            get
            {
                return this.valorPrincipalImpressaoField;
            }
            set
            {
                this.valorPrincipalImpressaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string valorTotal
        {
            get
            {
                return this.valorTotalField;
            }
            set
            {
                this.valorTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(boletoRetorno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/")]
    public partial class mensagemRetorno
    {
        
        private string mensagemRetorno1Field;
        
        private string tipoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensagemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mensagemRetorno1
        {
            get
            {
                return this.mensagemRetorno1Field;
            }
            set
            {
                this.mensagemRetorno1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoRetorno
        {
            get
            {
                return this.tipoRetornoField;
            }
            set
            {
                this.tipoRetornoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarCodigoBarrasIPVA", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarCodigoBarrasIPVARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string renavam;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfCnpjIE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroCota;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataVencimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string periodoReferencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoReceita;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public solicitarCodigoBarrasIPVARequest()
        {
        }
        
        public solicitarCodigoBarrasIPVARequest(string renavam, string cpfCnpjIE, string numeroDocumento, string numeroCota, string valorTotal, string dataVencimento, string periodoReferencia, string codigoOrgao, string codigoReceita, string tokenAcesso)
        {
            this.renavam = renavam;
            this.cpfCnpjIE = cpfCnpjIE;
            this.numeroDocumento = numeroDocumento;
            this.numeroCota = numeroCota;
            this.valorTotal = valorTotal;
            this.dataVencimento = dataVencimento;
            this.periodoReferencia = periodoReferencia;
            this.codigoOrgao = codigoOrgao;
            this.codigoReceita = codigoReceita;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarCodigoBarrasIPVAResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarCodigoBarrasIPVAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IntegrationDarService.boletoRetorno @return;
        
        public solicitarCodigoBarrasIPVAResponse()
        {
        }
        
        public solicitarCodigoBarrasIPVAResponse(IntegrationDarService.boletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarCodigoBarras", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarCodigoBarrasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfCnpjIE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataVencimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string periodoReferencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoReceita;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public solicitarCodigoBarrasRequest()
        {
        }
        
        public solicitarCodigoBarrasRequest(string cpfCnpjIE, string numeroDocumento, string valorTotal, string dataVencimento, string periodoReferencia, string codigoOrgao, string codigoReceita, string tokenAcesso)
        {
            this.cpfCnpjIE = cpfCnpjIE;
            this.numeroDocumento = numeroDocumento;
            this.valorTotal = valorTotal;
            this.dataVencimento = dataVencimento;
            this.periodoReferencia = periodoReferencia;
            this.codigoOrgao = codigoOrgao;
            this.codigoReceita = codigoReceita;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarCodigoBarrasResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarCodigoBarrasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IntegrationDarService.boletoRetorno @return;
        
        public solicitarCodigoBarrasResponse()
        {
        }
        
        public solicitarCodigoBarrasResponse(IntegrationDarService.boletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarCodigoBarrasPDF", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarCodigoBarrasPDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfCnpjIE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataVencimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string periodoReferencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoReceita;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public solicitarCodigoBarrasPDFRequest()
        {
        }
        
        public solicitarCodigoBarrasPDFRequest(string cpfCnpjIE, string numeroDocumento, string valorTotal, string dataVencimento, string periodoReferencia, string codigoOrgao, string codigoReceita, string tokenAcesso)
        {
            this.cpfCnpjIE = cpfCnpjIE;
            this.numeroDocumento = numeroDocumento;
            this.valorTotal = valorTotal;
            this.dataVencimento = dataVencimento;
            this.periodoReferencia = periodoReferencia;
            this.codigoOrgao = codigoOrgao;
            this.codigoReceita = codigoReceita;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarCodigoBarrasPDFResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarCodigoBarrasPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IntegrationDarService.boletoRetorno @return;
        
        public solicitarCodigoBarrasPDFResponse()
        {
        }
        
        public solicitarCodigoBarrasPDFResponse(IntegrationDarService.boletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarDarIcms", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarDarIcmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoReceita;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inscricao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string substitoTributo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string periodoReferencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataVencimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataPagamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taxaEmissao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public solicitarDarIcmsRequest()
        {
        }
        
        public solicitarDarIcmsRequest(string codigoReceita, string inscricao, string substitoTributo, string periodoReferencia, string dataVencimento, string dataPagamento, string taxaEmissao, string valorTotal, string numeroDocumento, string codigoOrgao, string tokenAcesso)
        {
            this.codigoReceita = codigoReceita;
            this.inscricao = inscricao;
            this.substitoTributo = substitoTributo;
            this.periodoReferencia = periodoReferencia;
            this.dataVencimento = dataVencimento;
            this.dataPagamento = dataPagamento;
            this.taxaEmissao = taxaEmissao;
            this.valorTotal = valorTotal;
            this.numeroDocumento = numeroDocumento;
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarDarIcmsResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarDarIcmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IntegrationDarService.boletoRetorno @return;
        
        public solicitarDarIcmsResponse()
        {
        }
        
        public solicitarDarIcmsResponse(IntegrationDarService.boletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarDarAInfracaoAvisoDeb", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarDarAInfracaoAvisoDebRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoReceita;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfCnpjIE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taxaEmissao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorParcial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public solicitarDarAInfracaoAvisoDebRequest()
        {
        }
        
        public solicitarDarAInfracaoAvisoDebRequest(string codigoReceita, string cpfCnpjIE, string numeroDocumento, string taxaEmissao, string valorParcial, string codigoOrgao, string tokenAcesso)
        {
            this.codigoReceita = codigoReceita;
            this.cpfCnpjIE = cpfCnpjIE;
            this.numeroDocumento = numeroDocumento;
            this.taxaEmissao = taxaEmissao;
            this.valorParcial = valorParcial;
            this.codigoOrgao = codigoOrgao;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarDarAInfracaoAvisoDebResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarDarAInfracaoAvisoDebResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IntegrationDarService.boletoRetorno @return;
        
        public solicitarDarAInfracaoAvisoDebResponse()
        {
        }
        
        public solicitarDarAInfracaoAvisoDebResponse(IntegrationDarService.boletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DocumentoArrecadacaoWSChannel : IntegrationDarService.DocumentoArrecadacaoWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DocumentoArrecadacaoWSClient : System.ServiceModel.ClientBase<IntegrationDarService.DocumentoArrecadacaoWS>, IntegrationDarService.DocumentoArrecadacaoWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DocumentoArrecadacaoWSClient() : 
                base(DocumentoArrecadacaoWSClient.GetDefaultBinding(), DocumentoArrecadacaoWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DocumentoArrecadacaoWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentoArrecadacaoWSClient(EndpointConfiguration endpointConfiguration) : 
                base(DocumentoArrecadacaoWSClient.GetBindingForEndpoint(endpointConfiguration), DocumentoArrecadacaoWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentoArrecadacaoWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DocumentoArrecadacaoWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentoArrecadacaoWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DocumentoArrecadacaoWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentoArrecadacaoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasIPVAResponse> IntegrationDarService.DocumentoArrecadacaoWS.solicitarCodigoBarrasIPVAAsync(IntegrationDarService.solicitarCodigoBarrasIPVARequest request)
        {
            return base.Channel.solicitarCodigoBarrasIPVAAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasIPVAResponse> solicitarCodigoBarrasIPVAAsync(string renavam, string cpfCnpjIE, string numeroDocumento, string numeroCota, string valorTotal, string dataVencimento, string periodoReferencia, string codigoOrgao, string codigoReceita, string tokenAcesso)
        {
            IntegrationDarService.solicitarCodigoBarrasIPVARequest inValue = new IntegrationDarService.solicitarCodigoBarrasIPVARequest();
            inValue.renavam = renavam;
            inValue.cpfCnpjIE = cpfCnpjIE;
            inValue.numeroDocumento = numeroDocumento;
            inValue.numeroCota = numeroCota;
            inValue.valorTotal = valorTotal;
            inValue.dataVencimento = dataVencimento;
            inValue.periodoReferencia = periodoReferencia;
            inValue.codigoOrgao = codigoOrgao;
            inValue.codigoReceita = codigoReceita;
            inValue.tokenAcesso = tokenAcesso;
            return ((IntegrationDarService.DocumentoArrecadacaoWS)(this)).solicitarCodigoBarrasIPVAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasResponse> IntegrationDarService.DocumentoArrecadacaoWS.solicitarCodigoBarrasAsync(IntegrationDarService.solicitarCodigoBarrasRequest request)
        {
            return base.Channel.solicitarCodigoBarrasAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasResponse> solicitarCodigoBarrasAsync(string cpfCnpjIE, string numeroDocumento, string valorTotal, string dataVencimento, string periodoReferencia, string codigoOrgao, string codigoReceita, string tokenAcesso)
        {
            IntegrationDarService.solicitarCodigoBarrasRequest inValue = new IntegrationDarService.solicitarCodigoBarrasRequest();
            inValue.cpfCnpjIE = cpfCnpjIE;
            inValue.numeroDocumento = numeroDocumento;
            inValue.valorTotal = valorTotal;
            inValue.dataVencimento = dataVencimento;
            inValue.periodoReferencia = periodoReferencia;
            inValue.codigoOrgao = codigoOrgao;
            inValue.codigoReceita = codigoReceita;
            inValue.tokenAcesso = tokenAcesso;
            return ((IntegrationDarService.DocumentoArrecadacaoWS)(this)).solicitarCodigoBarrasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasPDFResponse> IntegrationDarService.DocumentoArrecadacaoWS.solicitarCodigoBarrasPDFAsync(IntegrationDarService.solicitarCodigoBarrasPDFRequest request)
        {
            return base.Channel.solicitarCodigoBarrasPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasPDFResponse> solicitarCodigoBarrasPDFAsync(string cpfCnpjIE, string numeroDocumento, string valorTotal, string dataVencimento, string periodoReferencia, string codigoOrgao, string codigoReceita, string tokenAcesso)
        {
            IntegrationDarService.solicitarCodigoBarrasPDFRequest inValue = new IntegrationDarService.solicitarCodigoBarrasPDFRequest();
            inValue.cpfCnpjIE = cpfCnpjIE;
            inValue.numeroDocumento = numeroDocumento;
            inValue.valorTotal = valorTotal;
            inValue.dataVencimento = dataVencimento;
            inValue.periodoReferencia = periodoReferencia;
            inValue.codigoOrgao = codigoOrgao;
            inValue.codigoReceita = codigoReceita;
            inValue.tokenAcesso = tokenAcesso;
            return ((IntegrationDarService.DocumentoArrecadacaoWS)(this)).solicitarCodigoBarrasPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarDarIcmsResponse> IntegrationDarService.DocumentoArrecadacaoWS.solicitarDarIcmsAsync(IntegrationDarService.solicitarDarIcmsRequest request)
        {
            return base.Channel.solicitarDarIcmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationDarService.solicitarDarIcmsResponse> solicitarDarIcmsAsync(string codigoReceita, string inscricao, string substitoTributo, string periodoReferencia, string dataVencimento, string dataPagamento, string taxaEmissao, string valorTotal, string numeroDocumento, string codigoOrgao, string tokenAcesso)
        {
            IntegrationDarService.solicitarDarIcmsRequest inValue = new IntegrationDarService.solicitarDarIcmsRequest();
            inValue.codigoReceita = codigoReceita;
            inValue.inscricao = inscricao;
            inValue.substitoTributo = substitoTributo;
            inValue.periodoReferencia = periodoReferencia;
            inValue.dataVencimento = dataVencimento;
            inValue.dataPagamento = dataPagamento;
            inValue.taxaEmissao = taxaEmissao;
            inValue.valorTotal = valorTotal;
            inValue.numeroDocumento = numeroDocumento;
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((IntegrationDarService.DocumentoArrecadacaoWS)(this)).solicitarDarIcmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarDarAInfracaoAvisoDebResponse> IntegrationDarService.DocumentoArrecadacaoWS.solicitarDarAInfracaoAvisoDebAsync(IntegrationDarService.solicitarDarAInfracaoAvisoDebRequest request)
        {
            return base.Channel.solicitarDarAInfracaoAvisoDebAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationDarService.solicitarDarAInfracaoAvisoDebResponse> solicitarDarAInfracaoAvisoDebAsync(string codigoReceita, string cpfCnpjIE, string numeroDocumento, string taxaEmissao, string valorParcial, string codigoOrgao, string tokenAcesso)
        {
            IntegrationDarService.solicitarDarAInfracaoAvisoDebRequest inValue = new IntegrationDarService.solicitarDarAInfracaoAvisoDebRequest();
            inValue.codigoReceita = codigoReceita;
            inValue.cpfCnpjIE = cpfCnpjIE;
            inValue.numeroDocumento = numeroDocumento;
            inValue.taxaEmissao = taxaEmissao;
            inValue.valorParcial = valorParcial;
            inValue.codigoOrgao = codigoOrgao;
            inValue.tokenAcesso = tokenAcesso;
            return ((IntegrationDarService.DocumentoArrecadacaoWS)(this)).solicitarDarAInfracaoAvisoDebAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocumentoArrecadacaoWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocumentoArrecadacaoWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://webas.sefaz.pi.gov.br/emiteDarService-homolog/DocumentoArrecadacaoWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DocumentoArrecadacaoWSClient.GetBindingForEndpoint(EndpointConfiguration.DocumentoArrecadacaoWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DocumentoArrecadacaoWSClient.GetEndpointAddress(EndpointConfiguration.DocumentoArrecadacaoWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            DocumentoArrecadacaoWSPort,
        }
    }
}
