//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationDarService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", ConfigurationName="IntegrationDarService.DocumentoArrecadacaoWS")]
    public interface DocumentoArrecadacaoWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarCodigoBarrasIPVAReq" +
            "uest", ReplyAction="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarCodigoBarrasIPVARes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasIPVAResponse> solicitarCodigoBarrasIPVAAsync(IntegrationDarService.solicitarCodigoBarrasIPVARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarCodigoBarrasRequest" +
            "", ReplyAction="http://ws.dar.sefaz.pi.gov.br/DocumentoArrecadacaoWS/solicitarCodigoBarrasRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mensagemRetorno))]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasResponse> solicitarCodigoBarrasAsync(IntegrationDarService.solicitarCodigoBarrasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/")]
    public partial class boletoRetorno : mensagemRetorno
    {
        
        private string codigoBarrasField;
        
        private string dataPagamentoField;
        
        private string linhaDigitavelField;
        
        private string numeroControleField;
        
        private string numeroDocumentoField;
        
        private string pagoField;
        
        private string valorPagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoBarras
        {
            get
            {
                return this.codigoBarrasField;
            }
            set
            {
                this.codigoBarrasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dataPagamento
        {
            get
            {
                return this.dataPagamentoField;
            }
            set
            {
                this.dataPagamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string linhaDigitavel
        {
            get
            {
                return this.linhaDigitavelField;
            }
            set
            {
                this.linhaDigitavelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numeroControle
        {
            get
            {
                return this.numeroControleField;
            }
            set
            {
                this.numeroControleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pago
        {
            get
            {
                return this.pagoField;
            }
            set
            {
                this.pagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string valorPago
        {
            get
            {
                return this.valorPagoField;
            }
            set
            {
                this.valorPagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(boletoRetorno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/")]
    public partial class mensagemRetorno
    {
        
        private string mensagemRetorno1Field;
        
        private string tipoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensagemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mensagemRetorno1
        {
            get
            {
                return this.mensagemRetorno1Field;
            }
            set
            {
                this.mensagemRetorno1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoRetorno
        {
            get
            {
                return this.tipoRetornoField;
            }
            set
            {
                this.tipoRetornoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarCodigoBarrasIPVA", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarCodigoBarrasIPVARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string renavam;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfCnpjIE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroCota;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataVencimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string periodoReferencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoReceita;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public solicitarCodigoBarrasIPVARequest()
        {
        }
        
        public solicitarCodigoBarrasIPVARequest(string renavam, string cpfCnpjIE, string numeroDocumento, string numeroCota, string valorTotal, string dataVencimento, string periodoReferencia, string codigoOrgao, string codigoReceita, string tokenAcesso)
        {
            this.renavam = renavam;
            this.cpfCnpjIE = cpfCnpjIE;
            this.numeroDocumento = numeroDocumento;
            this.numeroCota = numeroCota;
            this.valorTotal = valorTotal;
            this.dataVencimento = dataVencimento;
            this.periodoReferencia = periodoReferencia;
            this.codigoOrgao = codigoOrgao;
            this.codigoReceita = codigoReceita;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarCodigoBarrasIPVAResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarCodigoBarrasIPVAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IntegrationDarService.boletoRetorno @return;
        
        public solicitarCodigoBarrasIPVAResponse()
        {
        }
        
        public solicitarCodigoBarrasIPVAResponse(IntegrationDarService.boletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarCodigoBarras", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarCodigoBarrasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpfCnpjIE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataVencimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string periodoReferencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoOrgao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoReceita;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenAcesso;
        
        public solicitarCodigoBarrasRequest()
        {
        }
        
        public solicitarCodigoBarrasRequest(string cpfCnpjIE, string numeroDocumento, string valorTotal, string dataVencimento, string periodoReferencia, string codigoOrgao, string codigoReceita, string tokenAcesso)
        {
            this.cpfCnpjIE = cpfCnpjIE;
            this.numeroDocumento = numeroDocumento;
            this.valorTotal = valorTotal;
            this.dataVencimento = dataVencimento;
            this.periodoReferencia = periodoReferencia;
            this.codigoOrgao = codigoOrgao;
            this.codigoReceita = codigoReceita;
            this.tokenAcesso = tokenAcesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarCodigoBarrasResponse", WrapperNamespace="http://ws.dar.sefaz.pi.gov.br/", IsWrapped=true)]
    public partial class solicitarCodigoBarrasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.dar.sefaz.pi.gov.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IntegrationDarService.boletoRetorno @return;
        
        public solicitarCodigoBarrasResponse()
        {
        }
        
        public solicitarCodigoBarrasResponse(IntegrationDarService.boletoRetorno @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DocumentoArrecadacaoWSChannel : IntegrationDarService.DocumentoArrecadacaoWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DocumentoArrecadacaoWSClient : System.ServiceModel.ClientBase<IntegrationDarService.DocumentoArrecadacaoWS>, IntegrationDarService.DocumentoArrecadacaoWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DocumentoArrecadacaoWSClient() : 
                base(DocumentoArrecadacaoWSClient.GetDefaultBinding(), DocumentoArrecadacaoWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DocumentoArrecadacaoWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentoArrecadacaoWSClient(EndpointConfiguration endpointConfiguration) : 
                base(DocumentoArrecadacaoWSClient.GetBindingForEndpoint(endpointConfiguration), DocumentoArrecadacaoWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentoArrecadacaoWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DocumentoArrecadacaoWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentoArrecadacaoWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DocumentoArrecadacaoWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentoArrecadacaoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasIPVAResponse> IntegrationDarService.DocumentoArrecadacaoWS.solicitarCodigoBarrasIPVAAsync(IntegrationDarService.solicitarCodigoBarrasIPVARequest request)
        {
            return base.Channel.solicitarCodigoBarrasIPVAAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasIPVAResponse> solicitarCodigoBarrasIPVAAsync(string renavam, string cpfCnpjIE, string numeroDocumento, string numeroCota, string valorTotal, string dataVencimento, string periodoReferencia, string codigoOrgao, string codigoReceita, string tokenAcesso)
        {
            IntegrationDarService.solicitarCodigoBarrasIPVARequest inValue = new IntegrationDarService.solicitarCodigoBarrasIPVARequest();
            inValue.renavam = renavam;
            inValue.cpfCnpjIE = cpfCnpjIE;
            inValue.numeroDocumento = numeroDocumento;
            inValue.numeroCota = numeroCota;
            inValue.valorTotal = valorTotal;
            inValue.dataVencimento = dataVencimento;
            inValue.periodoReferencia = periodoReferencia;
            inValue.codigoOrgao = codigoOrgao;
            inValue.codigoReceita = codigoReceita;
            inValue.tokenAcesso = tokenAcesso;
            return ((IntegrationDarService.DocumentoArrecadacaoWS)(this)).solicitarCodigoBarrasIPVAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasResponse> IntegrationDarService.DocumentoArrecadacaoWS.solicitarCodigoBarrasAsync(IntegrationDarService.solicitarCodigoBarrasRequest request)
        {
            return base.Channel.solicitarCodigoBarrasAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationDarService.solicitarCodigoBarrasResponse> solicitarCodigoBarrasAsync(string cpfCnpjIE, string numeroDocumento, string valorTotal, string dataVencimento, string periodoReferencia, string codigoOrgao, string codigoReceita, string tokenAcesso)
        {
            IntegrationDarService.solicitarCodigoBarrasRequest inValue = new IntegrationDarService.solicitarCodigoBarrasRequest();
            inValue.cpfCnpjIE = cpfCnpjIE;
            inValue.numeroDocumento = numeroDocumento;
            inValue.valorTotal = valorTotal;
            inValue.dataVencimento = dataVencimento;
            inValue.periodoReferencia = periodoReferencia;
            inValue.codigoOrgao = codigoOrgao;
            inValue.codigoReceita = codigoReceita;
            inValue.tokenAcesso = tokenAcesso;
            return ((IntegrationDarService.DocumentoArrecadacaoWS)(this)).solicitarCodigoBarrasAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocumentoArrecadacaoWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocumentoArrecadacaoWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://webas.sefaz.pi.gov.br/emiteDarService-homolog/DocumentoArrecadacaoWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DocumentoArrecadacaoWSClient.GetBindingForEndpoint(EndpointConfiguration.DocumentoArrecadacaoWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DocumentoArrecadacaoWSClient.GetEndpointAddress(EndpointConfiguration.DocumentoArrecadacaoWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            DocumentoArrecadacaoWSPort,
        }
    }
}
